### PR TITLE
Add EchoPro and HakeIGP projects

### PR DESCRIPTION
**Pull request by emiliom**
Adds the 2 projects in #26

### CODE REVIEW

**Comment by emiliom** [comment]
wow, this CI takes a really long time to run!

**Comment by leewujung** [comment]
Well, I think this is the same build hanging problem as before -- build went through on my second re-run. I'll merge this and put in an issue for us to keep track of it, or perhaps some updates of the hugo action would resolve this.

**Comment by emiliom** [comment]
Thanks. Unlike last time, here I submitted a proper PR. 
Anyway, take a look at the actual content, including the keywords (I wasn't sure sure what to enter) and Funding agency.

I have the HakeIGP entry ready to go. I'll add it to this PR in a minute

**Comment by leewujung** [comment]
I tweaked the wording a bit to make the EchoPro description less convoluted, the IGP one looks good. I'll merge this now.

**Pull request merged**
