### PR TITLE
Update people section

### PR DESCRIPTION
**Pull request by leewujung**

### CODE REVIEW

**Comment by emiliom** [comment]
I like having an "Alumni" section. Comments:

- I think it's better to link to the alumni's preferred web site (LinkedIn, github, whatever) rather than for us to maintain their old personnel summary page, as you're doing with Kavin. We can also list the start-end years they were part of the group, and what position they held. 
- Why not do the same with Ali (her name is dropped)? And Jordana and Keith?

**Comment by leewujung** [comment]
I am fine with changing Kavin's old bio to LinkedIn, but with the template the headshot probably needs to be there -- I think it is better to just have names the links -- I could look into that later. I did think it is weird to have the old bio there, but that was the path of least work last night.

For Ali, Keith, and Jordana - I dropped their names because I don't think they have spent enough time in the group to be an integral part of it or actually contributed to the projects. Happy to discuss this.

**Comment by emiliom** [comment]
> I am fine with changing Kavin's old bio to LinkedIn, but with the template the headshot probably needs to be there -- I think it is better to just have names the links -- I could look into that later. I did think it is weird to have the old bio there, but that was the path of least work last night.

Ah. So, a stub person page has to exist in order for the person to show up at all?!

> For Ali, Keith, and Jordana - I dropped their names because I don't think they have spent enough time in the group to be an integral part of it or actually contributed to the projects. Happy to discuss this.

We can discuss elsewhere, some other time.

**Comment by leewujung** [comment]
> Ah. So, a stub person page has to exist in order for the person to show up at all?!

I think so, but there may be some short cut around it.

**Comment by leewujung** [comment]
Seems like this is what we need: https://github.com/wowchemy/wowchemy-hugo-themes/issues/1414
Not sure if it works with the updated version, but it's probably worth giving it a try.

**Pull request merged**
