### PR TITLE
Testing featured.jpg in Symposium 2023 talk

### PR DESCRIPTION
**Pull request by aditya-uw**
I have been using this featured.jpg functionality in my personal page. [Here is an example from my page.](https://aditya-uw.github.io/talk/investigation-of-duty-cycles-in-passive-acoustic-bat-monitoring/)

I wanted to see if the website preview rendered it similarly if I added the featured.jpg in the talk folder. @leewujung have you known of this? I'm asking to see if it was a decision to not have pictures like this because maybe not all events have pictures.

I also removed an accidental .DS_Store that got merged... sorry, macOS is very annoying. I could also modify the .gitignore to ignore .DS_Store files if you're okay with that?

### CODE REVIEW

**Comment by leewujung** [comment]
Yes I know this but have not had energy to add pics for all links.

Yes feel free to update .gitignore.

It is good practice to not do `git add *` though, you should always be explicit about what you are adding, and you typically don't get .DS_Store that way.

**Comment by leewujung** [comment]
Also, I see that you have some commits from the already merged PR. Make sure to pull the upstream and resolve conflicts (if any) when you PR!

**Comment by aditya-uw** [comment]
I see, then I'll stay away from adding the pic! I like consistency :)

And yes I'll pull and only add the changes I'm talking about. Also, I'll try to practice good git ettiquete then and just remove the .DS_Store file w/out updating .gitignore.

**Comment by leewujung** [comment]
Oh I actually think it is good to add a pic, I was just thinking about adding a diagram for the software project yesterday. I think you should absolutely have it!

Please do update .gitignore though -- since it's something many people would do. :P

**Comment by leewujung** [comment]
Ugh this workflow hanging thing is so annoying... at some point we should fix it, or use another framework altogether!

**Comment by aditya-uw** [comment]
Yes, like seriously thank you for cancelling jobs when they go on, maybe is there an action we can make to auto-cancel jobs that go on for longer than something like 5 mins.

**Comment by aditya-uw** [comment]
But the hanging itself is also a problem because we cannot see the previews

**Comment by leewujung** [comment]
> maybe is there an action we can make to auto-cancel jobs that go on for longer than something like 5 mins

Oh that is a great idea...!

**Comment by leewujung** [comment]
Looks like we're all good? Should I merge?

**Comment by aditya-uw** [comment]
yes!

**Pull request merged**
