### PR TITLE
Hake ML Update

### PR DESCRIPTION
**Pull request by ctuguinay**
* Added workflow image

### CODE REVIEW

**Comment by ctuguinay** [comment]
@valentina-s @leewujung Let me know what you think of these changes. I am still trying to figure out how to get rid of the aliasing here to improve image quality though.

**Comment by valentina-s** [comment]
Thanks @ctuguinay! 
- [ ]  Could you add a caption to the image (you can make it part of the image if it is easier so that it has a different font from the main text). 
- [ ] To remove the aliasing, you should store in `.png` instead of `.jpg`, as `jpg`'s algorithm is particularly bad at that. 
- [ ] Also if you can use a different font for the packages: like the courier font, the names may stand out? 
- [ ] I think the image can go after the discussion of the workflow.
- [ ] Could you add one more sentence after you mention the packages, that this allows us to organize data in a format suitable for deep learning and train models to predict regions of interest in echograms.

We could expand a bit on the content after that.

**Review by valentina-s — APPROVED** [review]
Thanks @ctuguinay!

- [ ] Could you add a caption to the image (you can make it part of the image if it is easier so that it has a different font from the main text).
- [ ]To remove the aliasing, you should store in .png instead of .jpg, as jpg's algorithm is particularly bad at that.
- [ ] Also if you can use a different font for the packages: like the courier font, the names may stand out?
- [ ] I think the image can go after the discussion of the workflow.
- [ ] Could you add one more sentence after you mention the packages, that this allows us to organize data in a format suitable for deep learning and train models to predict regions of interest in echograms.
We could expand a bit on the content after that.

**Comment by ctuguinay** [comment]
@valentina-s Thanks for the review! I incorporated your changes. Let me know if what I added to the pipeline makes sense or not. What I was trying to get with that addition was that Echopype and Echoregions transforms Echoview and Echosounder data into data products that can be used by many open-source repositories (ML repos just being one type of such repos), which is very powerful.

**Comment by valentina-s** [comment]
This image is still a low resolution. I tried to save at higher resolution from the slides. See, if you like it. Also here is a link to the slides if you want to edit something: [slide](https://docs.google.com/presentation/d/1K7dQsC_QPcXRT4ztABUCnhMDg_A30Uwby0utwZ3fhro/edit?usp=sharing)

featured

**Comment by valentina-s** [comment]
@ctuguinay could you update the image so we merge it. Thanks!

**Comment by ctuguinay** [comment]
@valentina-s I added your higher resolution image. I also didn't specify width and height and allowed the CSS to decide what to do with it in this case. I think this looks better, but what is displayed on the netlify deployment is still lower resolution since the image was resized to match the column width of the project page.

**Comment by valentina-s** [comment]
I see, it looks ok when one zooms in. I think it is good enough for now!

**Comment by ctuguinay** [comment]
@valentina-s could you merge this if it's good? I don't have permissions to merge

**Comment by valentina-s** [comment]
@ctuguinay I did not realize you did not have permissions. Mergin now!

**Pull request merged**
