### PR TITLE
Update Liuyixin's description page

### PR DESCRIPTION
**Pull request by FXF48-Mila**
To change the description page of Liuyixin (Mila) Shao.

### CODE REVIEW

**Comment by FXF48-Mila** [comment]
Hi @leewujung and @valentina-s, I have completed the PR to revise my self-description, can you review my changes?

**Review by valentina-s — APPROVED** [review]
@FXF48-Mila Looks good to me!

**Comment by FXF48-Mila** [comment]
@valentina-s I cannot push it from my side. Can you push it? Thank you!

**Comment by leewujung** [comment]
Ah right you don't have push permission. I'll merge it now. Thanks!

**Pull request merged**
