### PR TITLE
Add WGFAST 2022 talks and update news

### PR DESCRIPTION
**Pull request by leewujung**
This PR includes:
- entries of the 2 talks we gave in WGFAST 2022
- updates on the News list, including the WGFAST 2022 talks and my upcoming keynote in the ASA Denver meeting

Addresses #42 , the slides used in WGFAST 2022 are nearly identical and more up to date, so I opted for that one.

### CODE REVIEW

**Comment by leewujung** [comment]
Re-run the deploy works so the preview link is live now.

**Comment by emiliom** [comment]
Thanks! Looks good.

> Addresses https://github.com/uw-echospace/group-website/issues/42 , the slides used in WGFAST 2022 are nearly identical and more up to date, so I opted for that one.

I agree that we don't really need to make the NCEI WCSD presentation pdf available separately. But I think it's still helpful for us to have an entry for that presentation, to have a complete record of public presentations to point to (and to remember, say, for project reports). The slide link can point to the same WGFAST pdf.

**Comment by leewujung** [comment]
I found it a little bizarre to have two identical talks right on top of each other. There is a "summary" entry that I left blank right now, how about I put in a sentence there to say that the same presentation is given at the NCEI workshop? This summary will show up immediately below the talk title, like how the summary is shown under some of the papers.

**Comment by emiliom** [comment]
> I found it a little bizarre to have two identical talks right on top of each other. 

Good point.

> There is a "summary" entry that I left blank right now, how about I put in a sentence there to say that the same presentation is given at the NCEI workshop? This summary will show up immediately below the talk title, like how the summary is shown under some of the papers.

I like that! Please include the date for the NCEI WCSD presentation, for our own reference.

**Comment by leewujung** [comment]
Done!

**Comment by emiliom** [comment]
Awesome, thanks! Looks great

**Comment by leewujung** [comment]
Thanks, I'll merge now!

**Pull request merged**
