### PR TITLE
added info

### PR DESCRIPTION
**Pull request by Linda189**

### CODE REVIEW

**Comment by Linda189** [comment]
@leewujung I added my info and a picture.

**Comment by leewujung** [comment]
Thanks @Linda189 ! Not to be nitpicking but do you want to crop your pic to make it a little larger?

**Comment by Linda189** [comment]
@leewujung yes i did

**Comment by leewujung** [comment]
Do you want to crop it further? Just thinking that your head is smaller than the others'.

**Comment by Linda189** [comment]
@leewujung I cropped it further now, does it look better?

**Comment by leewujung** [comment]
Yes, looks great! I'll merge this now.

**Pull request merged**
