### PR TITLE
add_varkrish_page

### PR DESCRIPTION
**Pull request by varun-krishanumakr**
Added all of the necesssary personal information to be part of the github page

### CODE REVIEW

**Comment by leewujung** [comment]
@varun-krishanumakr : Your image is not showing up in the preview. Can you take a look?

**Comment by varun-krishanumakr** [comment]
@leewujung I just removed the image and added another one, can you see if that worked?

**Comment by leewujung** [comment]
You should be able to check yourself. Ping me when you have everything set up. :)

**Comment by valentina-s** [comment]
@varun-krishanumakr your image does not show: you can check by clicking on "Show all checks" above, and then on the "Details" link next to Netlify. The name of the image should be "avatar.jpg" so that it displays.

**Comment by varun-krishanumakr** [comment]
@valentina-s @leewujung I think it works now! Sorry for taking so long on figuring this out!

**Pull request merged**
